wheel_fl:
  display_name: Front Left Wheel
  type: WHEEL
  controller:
    package: dynamixel_controllers
    module: joint_torque_controller
    type: JointTorqueController
  joint_name: fl
  joint_speed: 1023
  motor:
    id: 1
    init: 0
    min: 0
    max: 4093
    invert: false

wheel_fr:
  display_name: Front Right Wheel
  type: WHEEL
  controller:
    package: dynamixel_controllers
    module: joint_torque_controller
    type: JointTorqueController
  joint_name: fr
  joint_speed: 1023
  motor:
    id: 2
    init: 0
    min: 0
    max: 4093
    invert: true

wheel_br:
  display_name: Back Right Wheel
  type: WHEEL
  controller:
    package: dynamixel_controllers
    module: joint_torque_controller
    type: JointTorqueController
  joint_name: br
  joint_speed: 1023
  motor:
    id: 3
    init: 0
    min: 0
    max: 4093
    invert: true

wheel_bl:
  display_name: Back Left Wheel
  type: WHEEL
  controller:
    package: dynamixel_controllers
    module: joint_torque_controller
    type: JointTorqueController
  joint_name: bl
  joint_speed: 1023
  motor:
    id: 4
    init: 0
    min: 0
    max: 4093
    invert: false

arm_base:
  display_name: Arm
  type: ABSOLUTE
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: base
  joint_speed: 0.5
  motor:
    id: 5
    init: 200
    min: 200
    max: 850

arm_wrist:
  display_name: Wrist
  type: ABSOLUTE
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: wrist
  joint_speed: 1.0
  motor:
    id: 6
    init: 173
    min: 173
    max: 810

arm_hand:
  display_name: Hand
  type: ABSOLUTE
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: hand
  joint_speed: 1.0
  motor:
    id: 7
    init: 150
    min: 150
    max: 870

test_hand:
  display_name: Test
  type: WHEEL
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: hand2
  joint_speed: 1.0
  motor:
    id: 7
    init: 150
    min: 150
    max: 870
