---
- hosts: pi_emu
  sudo: yes
  tasks:
  - name: Backup network interfaces file, gets removed in purge.
    command: cp /etc/network/interfaces /etc/network/interfaces.backup
  - name: Remove unnecessary packages
    command: apt-get -y purge xserver.* x11.* xarchiver xauth xkb-data console-setup xinit lightdm lxde.* python-tk python3-tk scratch gtk.* libgtk.* openbox libxt.* lxpanel gnome.* libqt.* libxcb.* libxfont.* lxmenu.* gvfs.* xdg-.* desktop.* tcl.* shared-mime-info penguinspuzzle omxplayer gsfonts
  - name: Autoremove anything left
    command: apt-get -y autoremove
  - name: Add local Australian mirror.
    apt_repository: repo='deb http://mirror.internode.on.net/pub/raspbian/raspbian/ wheezy main contrib non-free rpi' state=present
  - name: Remove default Raspbian repo
    apt_repository: repo='deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi' state=absent
  - name: Upgrade packages
    apt: upgrade=yes update_cache=yes
  - name: Make sure we have packages Ansible requires
    command: apt-get -y install python-apt python-pycurl
  - name: Move network interfaces back.
    command: mv /etc/network/interfaces.backup /etc/network/interfaces
  - name: Reboot the machine
    command: reboot
    async: 0
    poll: 0
    ignore_errors: true
  - name: Wait for Pi to come back
    local_action: wait_for host={{ inventory_hostname }}
                  state=started
    sudo: false
