---
# Update the Raspberry Pi firmware.
- hosts: pi_emu
  sudo: yes
  tasks:
    - name: Update APT
      apt: update_cache=yes cache_valid_time=3600
    - name: Upgrade APT
      apt: upgrade=full
    - name: Upgrade Firmware
      # This seems to hang, but updates the firmware anyway?
      shell: echo "y" | rpi-update
