---
# What we need for the configure UI.
- hosts: pi_emu
  sudo: yes
  tasks:
    - name: Install the Python Dialog package
      apt: name=python-dialog,python-configobj state=present
    - name: Create OARK directory.
      file: path=/opt/oark state=directory owner=pi group=pi mode=0775 recurse=yes
    - name: Copy config tool.
      copy: src=../Projects/oark/config-tool dest=/opt/oark/
    - name: Remove raspi-config from startup.
      file: path=/etc/profile.d/raspi-config.sh state=absent
    - name: Copy UI config script.
      copy: src=../Projects/oark/utils/config-ui.sh dest=/etc/profile.d/config-ui.sh owner=root group=root mode=755
