---
# Install the OARK files and set up to run
- hosts: pi_emu
  sudo: yes
  tasks:
    - name: Create OARK directory.
      file: path=/opt/oark state=directory owner=pi group=pi mode=0775 recurse=yes
    - name: Copy OARK runtime files.
      copy: src=../Projects/oark/ros-pkg dest=/opt/oark/
    - name: Create missing symlink
      file: path=/opt/oark/ros-pkg/src/CMakeLists.txt src=/opt/ros/indigo/share/catkin/cmake/toplevel.cmake state=link
    - name: Build OARK ROS package.
      shell: bash build-dynamite.sh
      args:
        chdir: /opt/oark/ros-pkg
    - name: Add Pi user to tty group for serial.
      user: name=pi groups=tty append=yes
    - name: Remove the console from the hardware serial port (kernel).
      shell: sed -i s/console=ttyAMA0,115200//g /boot/cmdline.txt
    - name: Remove the serial console from inittab (tty)
      lineinfile:
        dest=/etc/inittab
        line="T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100"
        state=absent
    - name: Copy utils.
      copy: src=../Projects/oark/utils dest=/opt/oark/
    - name: Copy startup file.
      copy: src=../Projects/oark/utils/oark dest=/etc/init.d/oark owner=root group=root mode=755
    - name: Set Emumini to run on startup
      command: update-rc.d oark defaults
