---
# Builds the dynamite ROS module.
- hosts: pi_emu
  tasks:
  - name: Copy the source code to the Pi for building
    copy: src=~/Projects/oark/ros-pkg dest=~/Projects/
  - name: Build the robot system
    shell: bash build-dynamite.sh
    args:
      chdir: ~/Projects/ros-pkg
  - name: Add Pi user to tty group for serial
    user: name=pi groups=tty append=yes
    sudo: yes
  - name: Remove the console from the hardware serial port
    shell: sed -i s/console=ttyAMA0,115200//g /boot/cmdline.txt
    sudo: yes
