# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # We don't need much, since the emulator is only single processor,
  # but this should help a little
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.provision :shell, path: "scripts/bootstrap.sh"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Generate SSH keypair, we will copy this into the Raspberry Pi image
  # so we don't need a password to SSH in.
  config.vm.provision :shell, privileged: false,
                      path: "scripts/generate-ssh-key.sh"

  # Kiln Agent Auth settings so it can pull down the latest version.
  config.vm.provision :file, source: "files/hgrc", destination: ".hgrc"
  config.vm.provision :shell, privileged: false, path: "scripts/pull-repo.sh"

  # Copy the Ansible host file for talking to the emulator.
  config.vm.provision :file, source: "files/ansible_hosts",
                      destination: ".ansible_hosts"

  # Disble SSH host key checking, since we're automating.
  config.vm.provision :file, source: "files/ansible.cfg",
                      destination: ".ansible.cfg"

  config.vm.provision :file, source: "files/playbooks",
                      destination: "ansible_playbooks"

  # Start building the Raspberry Pi image.
  config.vm.provision :shell, privileged: false,
                      path: "scripts/bootstrap-raspbian.sh"
end
