# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.provision :shell, path: "scripts/bootstrap.sh"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Kiln Agent Auth settings so it can pull down the latest version.
  config.vm.provision :file, source: "hgrc", destination: ".hgrc"
  config.vm.provision :shell, privileged: false, path: "scripts/pull-repo.sh"

  # If we have a Raspbian image in the files directory already then
  # copy it into the virtual machine to save time.
  if File.exist?("./files/raspbian_latest.zip") then
    config.vm.provision :file, source: "files/raspbian_latest.zip",
                        destination: "Projects/oark/build-tools/emulation"
  end
end
